# cargo-release configuration for automated releases

# Global settings
consolidate-commits = true
pre-release-commit-message = "chore: release v{{version}}"
tag-message = "Release v{{version}}"
tag-name = "v{{version}}"

# Don't publish, let CI handle it
publish = false
push = true
push-remote = "origin"

# Workspace-wide replacements
[[pre-release-replacements]]
file = "Cargo.toml"
search = 'version = ".*"'
replace = 'version = "{{version}}"'
exactly = 1

[[pre-release-replacements]]
file = "README.md"
search = 'clickhouse-arrow = "[^"]*"'
replace = 'clickhouse-arrow = "{{version}}"'

# Package-specific configurations
[package.clickhouse-arrow]
[[package.clickhouse-arrow.pre-release-replacements]]
file = "README.md"
search = 'clickhouse-arrow = "[^"]*"'
replace = 'clickhouse-arrow = "{{version}}"'

[package.clickhouse-arrow-derive]
[[package.clickhouse-arrow-derive.pre-release-replacements]]
file = "README.md"
search = 'clickhouse-arrow = "[^"]*"'
replace = 'clickhouse-arrow = "{{version}}"'