# cargo-release configuration for automated releases

# Global settings
consolidate-commits = true
pre-release-commit-message = "chore: release v{{version}}"
tag-message = "Release v{{version}}"
tag-name = "v{{version}}"

pre-release-replacements = [
    # Update workspace version in root Cargo.toml
    { file = "Cargo.toml", search = 'version = ".*"', replace = 'version = "{{version}}"', exactly = 1 },
    # Update README installation instructions
    { file = "README.md", search = 'clickhouse-arrow = "[^"]*"', replace = 'clickhouse-arrow = "{{version}}"' },
    { file = "clickhouse-arrow/README.md", search = 'clickhouse-arrow = "[^"]*"', replace = 'clickhouse-arrow = "{{version}}"' },
]

# Don't publish, let CI handle it
publish = false
push = true
push-remote = "origin"