# cargo-release configuration for automated releases

consolidate-commits = true
pre-release-commit-message = "chore: release v{{version}}"
tag-message = "Release v{{version}}"
tag-name = "v{{version}}"
pre-release-replacements = [
    # Update workspace version
    { file = "./Cargo.toml", search = '\[workspace\.package\]\nversion = ".*"', replace = '[workspace.package]\nversion = "{{version}}"', exactly = 1 },
    # Update README installation instructions
    { file = "README.md", search = 'clickhouse-arrow = "[^"]*"', replace = 'clickhouse-arrow = "{{version}}"', min = 0 },
]

# Don't publish, let CI handle it
publish = false
push = true
push-remote = "origin"
