[package]
name = "clickhouse_native_derive"
version = "0.2.0"
edition.workspace = true

[lib]
name = "clickhouse_native_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1.0"
syn = "2"
